import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Blockchain Mail',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${inter.className} h-screen p-3`}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
